version: 2
jobs:
  build-and-test:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk
    steps:
      - checkout
      - run: dotnet build -c Release
      - run: dotnet test ContentPOC.Integration
      - run: dotnet test ContentPOC.Test
  publish:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk
    steps:
      - checkout
      - restore_cache:
          key: out-v2-{{ .Branch }}-{{ .Revision }}
      - run: dotnet publish -c Release -o ../publish  && chmod +x publish
      - save_cache:
          key: out-v2-{{ .Branch }}-{{ .Revision }}
          paths:
            - publish  
  heroku-push:
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: out-v2-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Setup Heroku
          command: chmod +x .circleci/setup-heroku.sh && .circleci/setup-heroku.sh worthington10tw-content
      - run:
          name: Push Heroku
          command: heroku container:login && heroku container:push web worker -a worthington10tw-content
  heroku-release:
    machine: true
    steps:
      - checkout
      - run:
          name: Setup Heroku
          command: chmod +x .circleci/setup-heroku.sh && .circleci/setup-heroku.sh worthington10tw-content
      - run: 
          name: Release Heroku
          command: heroku container:login && heroku container:release web --app worthington10tw-content
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build-and-test
      - publish:
          requires:
            - build-and-test
      - heroku-push:
          context: hello
          requires:
            - publish
      - heroku-release:
          context: hello
          requires:
            - heroku-push