version: 2
jobs:
  build-and-test:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk
    steps:
      - checkout
      - run: dotnet build -c Release
      - run: dotnet test ContentPOC.Integration
      - run: dotnet test ContentPOC.Test
  publish:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk
    steps:
      - checkout   
      - run: dotnet publish -c Release -o ../publish  && chmod +x publish
      - save_cache:
          key: out-v2-{{ .Branch }}-{{ .Revision }}
          paths:
            - publish
  heroku-push-from-publish:
    machine: true
    steps:
      - checkout
      #TODO this causes permission issue
      - restore_cache:
          key: out-v1-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Setup Heroku
          command: chmod +x .circleci/setup-heroku.sh && .circleci/setup-heroku.sh worthington10tw-content-poc
      - run: heroku container:login
      - run: heroku container:push web -f FromPublish.dockerfile -a worthington10tw-content-poc           
  heroku-push:
    machine: true
    steps:
      - checkout  
      - run:
          name: Setup Heroku
          command: chmod +x .circleci/setup-heroku.sh && .circleci/setup-heroku.sh worthington10tw-content-poc
      - run:
          name: Push Heroku
          command: heroku container:login && heroku stack:set container && heroku container:push web -a worthington10tw-content-poc
  heroku-release:
    context: hello
    machine: true
    steps:
      - checkout
      - run:
          name: Setup Heroku
          command: chmod +x .circleci/setup-heroku.sh && .circleci/setup-heroku.sh worthington10tw-content-poc
      - run: 
          name: Release Heroku
          command: heroku container:login && heroku stack:set container && heroku container:release web -a worthington10tw-content-poc
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build-and-test
      - publish:
          requires:
            - build-and-test
      # cache permission issue causing cache fetch to fail
      # publishing in docker build as a temp fix
      # - heroku-push-from-publish:
      #     context: hello
      #     requires:
      #       - publish  
      - heroku-push:
          context: hello
          requires:
            - publish
      - heroku-release:
          context: hello
          requires:
            - heroku-push